-- Dua Daily — MySQL 8+ schema. Import into a database named dua_daily.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `users` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`name` varchar(255) NOT NULL,`email` varchar(255) NOT NULL,`email_verified_at` timestamp NULL DEFAULT NULL,`password` varchar(255) NOT NULL,`remember_token` varchar(100) DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `users_email_unique` (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `categories` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`name` varchar(80) NOT NULL,`icon` varchar(40) NOT NULL DEFAULT '✦',`color` varchar(30) NOT NULL DEFAULT 'sage',`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `categories_name_unique` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `duas` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`title` varchar(180) NOT NULL,`category_id` bigint unsigned NOT NULL,`subcategory` varchar(100) DEFAULT NULL,`arabic` longtext,`transliteration` longtext,`translation` longtext,`reference` varchar(180) DEFAULT NULL,`notes` text,`is_favorite` tinyint(1) NOT NULL DEFAULT 0,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `duas_category_id_subcategory_index` (`category_id`,`subcategory`),CONSTRAINT `duas_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notes` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`title` varchar(160) NOT NULL,`body` longtext,`pinned` tinyint(1) NOT NULL DEFAULT 0,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sessions` (`id` varchar(255) NOT NULL,`user_id` bigint unsigned DEFAULT NULL,`ip_address` varchar(45) DEFAULT NULL,`user_agent` text,`payload` longtext NOT NULL,`last_activity` int NOT NULL,PRIMARY KEY (`id`),KEY `sessions_user_id_index` (`user_id`),KEY `sessions_last_activity_index` (`last_activity`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;
-- After importing and configuring .env, run `php artisan db:seed` to create the starter admin and categories.
