-- Dua Daily — MySQL 8+ schema. Import into a database named dua_daily.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS `users` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`name` varchar(255) NOT NULL,`email` varchar(255) NOT NULL,`email_verified_at` timestamp NULL DEFAULT NULL,`password` varchar(255) NOT NULL,`remember_token` varchar(100) DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `users_email_unique` (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `categories` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`name` varchar(80) NOT NULL,`icon` varchar(40) NOT NULL DEFAULT '✦',`color` varchar(30) NOT NULL DEFAULT 'sage',`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `categories_name_unique` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `duas` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`title` varchar(180) NOT NULL,`category_id` bigint unsigned NOT NULL,`subcategory` varchar(100) DEFAULT NULL,`arabic` longtext,`transliteration` longtext,`translation` longtext,`reference` varchar(180) DEFAULT NULL,`notes` text,`is_favorite` tinyint(1) NOT NULL DEFAULT 0,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `duas_category_id_subcategory_index` (`category_id`,`subcategory`),CONSTRAINT `duas_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `notes` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`title` varchar(160) NOT NULL,`body` longtext,`pinned` tinyint(1) NOT NULL DEFAULT 0,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `sessions` (`id` varchar(255) NOT NULL,`user_id` bigint unsigned DEFAULT NULL,`ip_address` varchar(45) DEFAULT NULL,`user_agent` text,`payload` longtext NOT NULL,`last_activity` int NOT NULL,PRIMARY KEY (`id`),KEY `sessions_user_id_index` (`user_id`),KEY `sessions_last_activity_index` (`last_activity`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=1;
-- After importing and configuring .env, run `php artisan db:seed` to create the starter admin and categories.


-- Story biographies and recurrence-based homepage story selection.
CREATE TABLE IF NOT EXISTS `stories` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`title` varchar(160) NOT NULL,`slug` varchar(180) NOT NULL,`story_type` varchar(40) NOT NULL DEFAULT 'prophet',`person_name` varchar(160) DEFAULT NULL,`era_label` varchar(120) DEFAULT NULL,`short_story` text,`life_journey` longtext,`reason` text,`full_story` longtext,`lessons` longtext,`sources` json DEFAULT NULL,`cover_url` varchar(1000) DEFAULT NULL,`is_published` tinyint(1) NOT NULL DEFAULT 0,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `stories_slug_unique` (`slug`),KEY `stories_type_published_index` (`story_type`,`is_published`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `story_schedules` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`story_id` bigint unsigned NOT NULL,`starts_on` date NOT NULL,`ends_on` date DEFAULT NULL,`repeat_rule` varchar(16) NOT NULL DEFAULT 'once',`priority` smallint unsigned NOT NULL DEFAULT 10,`is_active` tinyint(1) NOT NULL DEFAULT 1,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),KEY `story_schedules_active_start_end_index` (`is_active`,`starts_on`,`ends_on`),CONSTRAINT `story_schedules_story_id_foreign` FOREIGN KEY (`story_id`) REFERENCES `stories` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `resources` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`title` varchar(180) NOT NULL,`slug` varchar(200) NOT NULL,`resource_type` varchar(32) NOT NULL DEFAULT 'islamic_link',`creator` varchar(180) DEFAULT NULL,`summary` text,`url` varchar(1500) NOT NULL,`cover_url` varchar(1000) DEFAULT NULL,`is_published` tinyint(1) NOT NULL DEFAULT 0,`is_featured` tinyint(1) NOT NULL DEFAULT 0,`published_at` date DEFAULT NULL,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `resources_slug_unique` (`slug`),KEY `resources_published_featured_date_index` (`is_published`,`is_featured`,`published_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `masail` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`title` varchar(180) NOT NULL,`slug` varchar(200) NOT NULL,`category` varchar(100) DEFAULT NULL,`question` text,`short_answer` text,`answer` longtext,`references` longtext,`is_published` tinyint(1) NOT NULL DEFAULT 0,`created_at` timestamp NULL DEFAULT NULL,`updated_at` timestamp NULL DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `masail_slug_unique` (`slug`),KEY `masail_category_published_index` (`category`,`is_published`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
